### PR TITLE
Change event log format according to Harvard's requirements.

### PR DESCRIPTION
**Pull request by smarnach**
I also took the opportunity to add some testing infrastructure.  I haven't tested the event logs on a real deployment, since our Dalite sandbox doesn't seem to be available anymore, and LTI is not available when testing locally.  The tests should cover the events sufficiently, though.

### CODE REVIEW

**Comment by antoviaque** [comment]
@smarnach I restarted the dalite sandbox, if it's useful - I had stopped it since we weren't using it anymore. It's at 54.149.53.180.

**Comment by e-kolpakov** [comment]
@smarnach this is all looking good, but how do I verify it? By looking into logs?

**Comment by smarnach** [comment]
@e-kolpakov Events will only be logged when LTI is available, so it's a bit difficult to actually test this.  Xavier restarted the sandbox, so I can deploy this to the sandbox later today.

That said, I had hoped that there is sufficient test coverage to not require manual testing.  This doesn't change anything in the UI (which always requires manual verification), so I think it's reasonable to trust in the automatic tests.

**Comment by e-kolpakov** [comment]
@smarnach ok, :+1:  than

**Comment by e-kolpakov** [comment]
@smarnach :+1:

**Pull request merged**
